//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_ChuyenMon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SP()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string AnhNho { get; set; }
        public string Anh1 { get; set; }
        public string Anh2 { get; set; }
        public string Anh3 { get; set; }
        public string TSKT { get; set; }
        public Nullable<bool> TieuBieu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string Hang { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string DVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
