//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_ChuyenMon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int Ma { get; set; }
        public Nullable<int> MaCM { get; set; }
        public string MotaNgan { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string Anh { get; set; }
        public string NguoiDang { get; set; }
        public Nullable<bool> TieuBieu { get; set; }
        public string LoaiTin { get; set; }
        public string TieuDe { get; set; }
    
        public virtual ChuyenMuc ChuyenMuc { get; set; }
    }
}
